server:
   port: 8100
spring:
   application:
      name: config-server
   cloud:
      config:
         label: main
         server:
            git:
               uri: https://github.com/siyin-ajie/spring-cloud-config.git
               search-path: spring-cloud-config
               username: 2507214578@qq.com
               password: ajie19960201ajie
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://eureka8000.com:8000/eureka/,http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/