server:
   port: 8001
spring:
   application:
      name: ajie-flowEngine
eureka:
   instance:
#注册中心指向start
      instance-id: ajie-flowEngine
      appname: ${spring.application.name}
   client:
      service-url:
         defaultZone: http://localhost:8888/eureka/