server:
  port: 8201
 
spring:
  application:
    name: ajie-test
 
#注册中心指向start    
eureka:
  instance:
    instance-id: ajie-test
    appname: ${spring.application.name}
  client: 
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://eureka8000.com:8000/eureka/,http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/