server:
   port: 8000
spring:
   application:
      name: eureka-server
eureka:
   instance:
      #hostname: eureka8000.com
      prefer-ip-address: true #使用ip进行注册
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         #defaultZone: http://localhost:8000/eureka/
         defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/