server:
   port: 8002
spring:
   application:
      name: eureka-server
eureka:
   instance:
      #hostname: eureka8002.com
      prefer-ip-address: true #使用ip进行注册
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         defaultZone: http://eureka8000.com:8000/eureka/,http://eureka8001.com:8001/eureka/